language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-albertocoding
  api_key:
    secure: BPsdxFNUTrdQWx29yu/Bp8sZJFVQtmGAY1qxzzK/HzMMgS5mlMchOp0hfz0HMjXnpix41x/Y1y2oBqHIZMDHlhENUPRUz4M4uNi0MCJde05D7DR/BsUwWfmqgz9j9AWm4HVNouPKPDPzTHT32p8ZxQDNGzctcwEJm9ATdqL6vVLd50/36KF83+EMnGQ4A8t54AcXOnhG0WBVGrpUKuq2HQmDjbSxaVor0fwtezFbvnCDl9kx8pH8pVZMtdcZdf3QVbndk/ZGAv581JpSTkYhY509KHAA6srBCCYpf8pi6H2A16pFrV+SGoOKQ8kpFX9gglRVzROpDDSdCHWzTKxG1TVgR2DIbCECw6yaM06rjFbUIxCPIvanV7fctxdGyGyRt4JSqk3BP8JKKNmODt14L4KpxaP6zJEEkzCz4xBWBvtNNe45HyfXmypDVuverDjLrO/5C9zhEVfAusE/19mpQZvY6EdQM51EMvVT635WOhylBKya2tzXwqLRP2EVOPnVjGqFMNWeRgOJOmjKJ9NuMFu3ymi7SSCOMwDEeHtI9e8U/m2/OyE/J8zBjwAAn1X42BEg6DP+haQvnBx1NzyiafDZljNQsNgEo0AFSgNYhsbKPIMpEaFZhLv7FGTbDZe1Ii5R8ltIfv66qi6Dz0CyNKmAuWNzvfLoH9ECbja971E=
